# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import accounts_api_service_pb2 as accounts__api__service__pb2


class AccountsApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetAccountInfo = channel.unary_unary(
        '/api.AccountsApi/GetAccountInfo',
        request_serializer=accounts__api__service__pb2.AccountReq.SerializeToString,
        response_deserializer=accounts__api__service__pb2.AccountRsp.FromString,
        )


class AccountsApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetAccountInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AccountsApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetAccountInfo': grpc.unary_unary_rpc_method_handler(
          servicer.GetAccountInfo,
          request_deserializer=accounts__api__service__pb2.AccountReq.FromString,
          response_serializer=accounts__api__service__pb2.AccountRsp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.AccountsApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
