# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: accounts_api_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='accounts_api_service.proto',
  package='api',
  syntax='proto3',
  serialized_pb=_b('\n\x1a\x61\x63\x63ounts_api_service.proto\x12\x03\x61pi\"!\n\nAccountReq\x12\x13\n\x0b\x61\x63\x63ountCode\x18\x01 \x01(\t\"!\n\nAccountRsp\x12\x13\n\x0b\x61\x63\x63ountInfo\x18\x01 \x01(\t2C\n\x0b\x41\x63\x63ountsApi\x12\x34\n\x0eGetAccountInfo\x12\x0f.api.AccountReq\x1a\x0f.api.AccountRsp\"\x00\x62\x06proto3')
)




_ACCOUNTREQ = _descriptor.Descriptor(
  name='AccountReq',
  full_name='api.AccountReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountCode', full_name='api.AccountReq.accountCode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=35,
  serialized_end=68,
)


_ACCOUNTRSP = _descriptor.Descriptor(
  name='AccountRsp',
  full_name='api.AccountRsp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountInfo', full_name='api.AccountRsp.accountInfo', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=103,
)

DESCRIPTOR.message_types_by_name['AccountReq'] = _ACCOUNTREQ
DESCRIPTOR.message_types_by_name['AccountRsp'] = _ACCOUNTRSP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AccountReq = _reflection.GeneratedProtocolMessageType('AccountReq', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTREQ,
  __module__ = 'accounts_api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.AccountReq)
  ))
_sym_db.RegisterMessage(AccountReq)

AccountRsp = _reflection.GeneratedProtocolMessageType('AccountRsp', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTRSP,
  __module__ = 'accounts_api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.AccountRsp)
  ))
_sym_db.RegisterMessage(AccountRsp)



_ACCOUNTSAPI = _descriptor.ServiceDescriptor(
  name='AccountsApi',
  full_name='api.AccountsApi',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=105,
  serialized_end=172,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetAccountInfo',
    full_name='api.AccountsApi.GetAccountInfo',
    index=0,
    containing_service=None,
    input_type=_ACCOUNTREQ,
    output_type=_ACCOUNTRSP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACCOUNTSAPI)

DESCRIPTOR.services_by_name['AccountsApi'] = _ACCOUNTSAPI

# @@protoc_insertion_point(module_scope)
