# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: monitor_api_service.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='monitor_api_service.proto',
  package='api',
  syntax='proto3',
  serialized_pb=_b('\n\x19monitor_api_service.proto\x12\x03\x61pi\"/\n\x0cSms127152114\x12\x0e\n\x06phones\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x02 \x01(\t\"?\n\x0cSms143865355\x12\x0e\n\x06phones\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"?\n\x0cSms143860379\x12\x0e\n\x06phones\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"?\n\x0cSms143865361\x12\x0e\n\x06phones\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"\x83\x01\n\x0cSms143866194\x12\x0e\n\x06phones\x18\x01 \x01(\t\x12\x0f\n\x07project\x18\x02 \x01(\t\x12\x10\n\x08\x61\x63\x63ount1\x18\x03 \x01(\t\x12\n\n\x02\x61\x31\x18\x04 \x01(\t\x12\n\n\x02\x62\x31\x18\x05 \x01(\t\x12\x10\n\x08\x61\x63\x63ount2\x18\x06 \x01(\t\x12\n\n\x02\x61\x32\x18\x07 \x01(\t\x12\n\n\x02\x62\x32\x18\x08 \x01(\t\"\x1c\n\nSendResult\x12\x0e\n\x06result\x18\x01 \x01(\t2\xae\x02\n\nMonitorApi\x12\x38\n\x10SendSms127152114\x12\x11.api.Sms127152114\x1a\x0f.api.SendResult\"\x00\x12\x38\n\x10SendSms143865355\x12\x11.api.Sms143865355\x1a\x0f.api.SendResult\"\x00\x12\x38\n\x10SendSms143860379\x12\x11.api.Sms143860379\x1a\x0f.api.SendResult\"\x00\x12\x38\n\x10SendSms143865361\x12\x11.api.Sms143865361\x1a\x0f.api.SendResult\"\x00\x12\x38\n\x10SendSms143866194\x12\x11.api.Sms143866194\x1a\x0f.api.SendResult\"\x00\x62\x06proto3')
)




_SMS127152114 = _descriptor.Descriptor(
  name='Sms127152114',
  full_name='api.Sms127152114',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phones', full_name='api.Sms127152114.phones', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='content', full_name='api.Sms127152114.content', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=81,
)


_SMS143865355 = _descriptor.Descriptor(
  name='Sms143865355',
  full_name='api.Sms143865355',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phones', full_name='api.Sms143865355.phones', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='project', full_name='api.Sms143865355.project', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='api.Sms143865355.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=146,
)


_SMS143860379 = _descriptor.Descriptor(
  name='Sms143860379',
  full_name='api.Sms143860379',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phones', full_name='api.Sms143860379.phones', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='project', full_name='api.Sms143860379.project', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='api.Sms143860379.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=211,
)


_SMS143865361 = _descriptor.Descriptor(
  name='Sms143865361',
  full_name='api.Sms143865361',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phones', full_name='api.Sms143865361.phones', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='project', full_name='api.Sms143865361.project', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='api.Sms143865361.status', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=213,
  serialized_end=276,
)


_SMS143866194 = _descriptor.Descriptor(
  name='Sms143866194',
  full_name='api.Sms143866194',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='phones', full_name='api.Sms143866194.phones', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='project', full_name='api.Sms143866194.project', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account1', full_name='api.Sms143866194.account1', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a1', full_name='api.Sms143866194.a1', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b1', full_name='api.Sms143866194.b1', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account2', full_name='api.Sms143866194.account2', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='a2', full_name='api.Sms143866194.a2', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='b2', full_name='api.Sms143866194.b2', index=7,
      number=8, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=279,
  serialized_end=410,
)


_SENDRESULT = _descriptor.Descriptor(
  name='SendResult',
  full_name='api.SendResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='api.SendResult.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=412,
  serialized_end=440,
)

DESCRIPTOR.message_types_by_name['Sms127152114'] = _SMS127152114
DESCRIPTOR.message_types_by_name['Sms143865355'] = _SMS143865355
DESCRIPTOR.message_types_by_name['Sms143860379'] = _SMS143860379
DESCRIPTOR.message_types_by_name['Sms143865361'] = _SMS143865361
DESCRIPTOR.message_types_by_name['Sms143866194'] = _SMS143866194
DESCRIPTOR.message_types_by_name['SendResult'] = _SENDRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Sms127152114 = _reflection.GeneratedProtocolMessageType('Sms127152114', (_message.Message,), dict(
  DESCRIPTOR = _SMS127152114,
  __module__ = 'monitor_api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.Sms127152114)
  ))
_sym_db.RegisterMessage(Sms127152114)

Sms143865355 = _reflection.GeneratedProtocolMessageType('Sms143865355', (_message.Message,), dict(
  DESCRIPTOR = _SMS143865355,
  __module__ = 'monitor_api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.Sms143865355)
  ))
_sym_db.RegisterMessage(Sms143865355)

Sms143860379 = _reflection.GeneratedProtocolMessageType('Sms143860379', (_message.Message,), dict(
  DESCRIPTOR = _SMS143860379,
  __module__ = 'monitor_api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.Sms143860379)
  ))
_sym_db.RegisterMessage(Sms143860379)

Sms143865361 = _reflection.GeneratedProtocolMessageType('Sms143865361', (_message.Message,), dict(
  DESCRIPTOR = _SMS143865361,
  __module__ = 'monitor_api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.Sms143865361)
  ))
_sym_db.RegisterMessage(Sms143865361)

Sms143866194 = _reflection.GeneratedProtocolMessageType('Sms143866194', (_message.Message,), dict(
  DESCRIPTOR = _SMS143866194,
  __module__ = 'monitor_api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.Sms143866194)
  ))
_sym_db.RegisterMessage(Sms143866194)

SendResult = _reflection.GeneratedProtocolMessageType('SendResult', (_message.Message,), dict(
  DESCRIPTOR = _SENDRESULT,
  __module__ = 'monitor_api_service_pb2'
  # @@protoc_insertion_point(class_scope:api.SendResult)
  ))
_sym_db.RegisterMessage(SendResult)



_MONITORAPI = _descriptor.ServiceDescriptor(
  name='MonitorApi',
  full_name='api.MonitorApi',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=443,
  serialized_end=745,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendSms127152114',
    full_name='api.MonitorApi.SendSms127152114',
    index=0,
    containing_service=None,
    input_type=_SMS127152114,
    output_type=_SENDRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendSms143865355',
    full_name='api.MonitorApi.SendSms143865355',
    index=1,
    containing_service=None,
    input_type=_SMS143865355,
    output_type=_SENDRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendSms143860379',
    full_name='api.MonitorApi.SendSms143860379',
    index=2,
    containing_service=None,
    input_type=_SMS143860379,
    output_type=_SENDRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendSms143865361',
    full_name='api.MonitorApi.SendSms143865361',
    index=3,
    containing_service=None,
    input_type=_SMS143865361,
    output_type=_SENDRESULT,
    options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendSms143866194',
    full_name='api.MonitorApi.SendSms143866194',
    index=4,
    containing_service=None,
    input_type=_SMS143866194,
    output_type=_SENDRESULT,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITORAPI)

DESCRIPTOR.services_by_name['MonitorApi'] = _MONITORAPI

# @@protoc_insertion_point(module_scope)
