# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import monitor_api_service_pb2 as monitor__api__service__pb2


class MonitorApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendSms127152114 = channel.unary_unary(
        '/api.MonitorApi/SendSms127152114',
        request_serializer=monitor__api__service__pb2.Sms127152114.SerializeToString,
        response_deserializer=monitor__api__service__pb2.SendResult.FromString,
        )
    self.SendSms143865355 = channel.unary_unary(
        '/api.MonitorApi/SendSms143865355',
        request_serializer=monitor__api__service__pb2.Sms143865355.SerializeToString,
        response_deserializer=monitor__api__service__pb2.SendResult.FromString,
        )
    self.SendSms143860379 = channel.unary_unary(
        '/api.MonitorApi/SendSms143860379',
        request_serializer=monitor__api__service__pb2.Sms143860379.SerializeToString,
        response_deserializer=monitor__api__service__pb2.SendResult.FromString,
        )
    self.SendSms143865361 = channel.unary_unary(
        '/api.MonitorApi/SendSms143865361',
        request_serializer=monitor__api__service__pb2.Sms143865361.SerializeToString,
        response_deserializer=monitor__api__service__pb2.SendResult.FromString,
        )
    self.SendSms143866194 = channel.unary_unary(
        '/api.MonitorApi/SendSms143866194',
        request_serializer=monitor__api__service__pb2.Sms143866194.SerializeToString,
        response_deserializer=monitor__api__service__pb2.SendResult.FromString,
        )


class MonitorApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendSms127152114(self, request, context):
    """send common template
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendSms143865355(self, request, context):
    """send service status template
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendSms143860379(self, request, context):
    """send market status alarm template
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendSms143865361(self, request, context):
    """send program status alarm template
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendSms143866194(self, request, context):
    """send index alarm template
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MonitorApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendSms127152114': grpc.unary_unary_rpc_method_handler(
          servicer.SendSms127152114,
          request_deserializer=monitor__api__service__pb2.Sms127152114.FromString,
          response_serializer=monitor__api__service__pb2.SendResult.SerializeToString,
      ),
      'SendSms143865355': grpc.unary_unary_rpc_method_handler(
          servicer.SendSms143865355,
          request_deserializer=monitor__api__service__pb2.Sms143865355.FromString,
          response_serializer=monitor__api__service__pb2.SendResult.SerializeToString,
      ),
      'SendSms143860379': grpc.unary_unary_rpc_method_handler(
          servicer.SendSms143860379,
          request_deserializer=monitor__api__service__pb2.Sms143860379.FromString,
          response_serializer=monitor__api__service__pb2.SendResult.SerializeToString,
      ),
      'SendSms143865361': grpc.unary_unary_rpc_method_handler(
          servicer.SendSms143865361,
          request_deserializer=monitor__api__service__pb2.Sms143865361.FromString,
          response_serializer=monitor__api__service__pb2.SendResult.SerializeToString,
      ),
      'SendSms143866194': grpc.unary_unary_rpc_method_handler(
          servicer.SendSms143866194,
          request_deserializer=monitor__api__service__pb2.Sms143866194.FromString,
          response_serializer=monitor__api__service__pb2.SendResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.MonitorApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
