# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import vir_exchange_api_service_pb2 as vir__exchange__api__service__pb2


class VirExOtcApiStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getExMarketDepth = channel.unary_unary(
        '/api.VirExOtcApi/getExMarketDepth',
        request_serializer=vir__exchange__api__service__pb2.DepthInfo.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.TradeInfos.FromString,
        )
    self.getOtcMarketDepth = channel.unary_unary(
        '/api.VirExOtcApi/getOtcMarketDepth',
        request_serializer=vir__exchange__api__service__pb2.DepthInfo.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.TradeInfos.FromString,
        )
    self.getMarketDepth = channel.unary_unary(
        '/api.VirExOtcApi/getMarketDepth',
        request_serializer=vir__exchange__api__service__pb2.MarketInfo.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.MarketInfoResult.FromString,
        )
    self.getAccountLeft = channel.unary_unary(
        '/api.VirExOtcApi/getAccountLeft',
        request_serializer=vir__exchange__api__service__pb2.AssetInfo.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.AssetResult.FromString,
        )
    self.createBuyOrder = channel.unary_unary(
        '/api.VirExOtcApi/createBuyOrder',
        request_serializer=vir__exchange__api__service__pb2.OrderInfo.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.OrderResult.FromString,
        )
    self.createSellOrder = channel.unary_unary(
        '/api.VirExOtcApi/createSellOrder',
        request_serializer=vir__exchange__api__service__pb2.OrderInfo.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.OrderResult.FromString,
        )
    self.createBuyLimitMakerOrder = channel.unary_unary(
        '/api.VirExOtcApi/createBuyLimitMakerOrder',
        request_serializer=vir__exchange__api__service__pb2.OrderInfo.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.OrderResult.FromString,
        )
    self.createSellLimitMakerOrder = channel.unary_unary(
        '/api.VirExOtcApi/createSellLimitMakerOrder',
        request_serializer=vir__exchange__api__service__pb2.OrderInfo.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.OrderResult.FromString,
        )
    self.cannelOrder = channel.unary_unary(
        '/api.VirExOtcApi/cannelOrder',
        request_serializer=vir__exchange__api__service__pb2.OrderDetail.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.OrderDetailResult.FromString,
        )
    self.checkOrder = channel.unary_unary(
        '/api.VirExOtcApi/checkOrder',
        request_serializer=vir__exchange__api__service__pb2.OrderDetail.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.OrderDetailResult.FromString,
        )
    self.getOrdersMatchResult = channel.unary_unary(
        '/api.VirExOtcApi/getOrdersMatchResult',
        request_serializer=vir__exchange__api__service__pb2.OrderMatcher.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.OrderMatcherResult.FromString,
        )
    self.getCurrentOrders = channel.unary_unary(
        '/api.VirExOtcApi/getCurrentOrders',
        request_serializer=vir__exchange__api__service__pb2.CurrentOrder.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.CurrentOrderResult.FromString,
        )
    self.getFinishedOrders = channel.unary_unary(
        '/api.VirExOtcApi/getFinishedOrders',
        request_serializer=vir__exchange__api__service__pb2.FinishedOrder.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FinishedOrderResult.FromString,
        )
    self.kline = channel.unary_unary(
        '/api.VirExOtcApi/kline',
        request_serializer=vir__exchange__api__service__pb2.KLine.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.KLineResult.FromString,
        )
    self.klineRSI = channel.unary_unary(
        '/api.VirExOtcApi/klineRSI',
        request_serializer=vir__exchange__api__service__pb2.KLineRSI.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.KLineRSIResult.FromString,
        )
    self.klineKDJ = channel.unary_unary(
        '/api.VirExOtcApi/klineKDJ',
        request_serializer=vir__exchange__api__service__pb2.KLineKDJ.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.KLineKDJResult.FromString,
        )
    self.klineBOLL = channel.unary_unary(
        '/api.VirExOtcApi/klineBOLL',
        request_serializer=vir__exchange__api__service__pb2.KLineBOLL.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.KLineBOLLResult.FromString,
        )
    self.futuresTicker = channel.unary_unary(
        '/api.VirExOtcApi/futuresTicker',
        request_serializer=vir__exchange__api__service__pb2.FuturesTicker.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesTickerResult.FromString,
        )
    self.futuresDepth = channel.unary_unary(
        '/api.VirExOtcApi/futuresDepth',
        request_serializer=vir__exchange__api__service__pb2.FuturesDepth.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesDepthResult.FromString,
        )
    self.futuresKLine = channel.unary_unary(
        '/api.VirExOtcApi/futuresKLine',
        request_serializer=vir__exchange__api__service__pb2.FuturesKLine.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesKLineResult.FromString,
        )
    self.futuresKLineRSI = channel.unary_unary(
        '/api.VirExOtcApi/futuresKLineRSI',
        request_serializer=vir__exchange__api__service__pb2.FuturesKLineRSI.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesKLineRSIResult.FromString,
        )
    self.futuresKLineKDJ = channel.unary_unary(
        '/api.VirExOtcApi/futuresKLineKDJ',
        request_serializer=vir__exchange__api__service__pb2.FuturesKLineKDJ.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesKLineKDJResult.FromString,
        )
    self.futuresKLineBOLL = channel.unary_unary(
        '/api.VirExOtcApi/futuresKLineBOLL',
        request_serializer=vir__exchange__api__service__pb2.FuturesKLineBOLL.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesKLineBOLLResult.FromString,
        )
    self.futuresIndex = channel.unary_unary(
        '/api.VirExOtcApi/futuresIndex',
        request_serializer=vir__exchange__api__service__pb2.FuturesIndex.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesIndexResult.FromString,
        )
    self.futuresEstimatedPrice = channel.unary_unary(
        '/api.VirExOtcApi/futuresEstimatedPrice',
        request_serializer=vir__exchange__api__service__pb2.FuturesEstimatedPrice.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesEstimatedPriceResult.FromString,
        )
    self.futuresTrade = channel.unary_unary(
        '/api.VirExOtcApi/futuresTrade',
        request_serializer=vir__exchange__api__service__pb2.FuturesTrade.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesTradeResult.FromString,
        )
    self.futuresCancel = channel.unary_unary(
        '/api.VirExOtcApi/futuresCancel',
        request_serializer=vir__exchange__api__service__pb2.FuturesCancel.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesCancelResult.FromString,
        )
    self.futuresBatchCancel = channel.unary_unary(
        '/api.VirExOtcApi/futuresBatchCancel',
        request_serializer=vir__exchange__api__service__pb2.FuturesBatchCancel.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesBatchCancelResult.FromString,
        )
    self.futuresCheckOrder = channel.unary_unary(
        '/api.VirExOtcApi/futuresCheckOrder',
        request_serializer=vir__exchange__api__service__pb2.FuturesCheckOrder.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesCheckOrderResult.FromString,
        )
    self.futuresOrders = channel.unary_unary(
        '/api.VirExOtcApi/futuresOrders',
        request_serializer=vir__exchange__api__service__pb2.FuturesOrders.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesOrdersResult.FromString,
        )
    self.futuresUserInfoFix = channel.unary_unary(
        '/api.VirExOtcApi/futuresUserInfoFix',
        request_serializer=vir__exchange__api__service__pb2.FuturesUserInfoFix.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesUserInfoFixResult.FromString,
        )
    self.futuresPositionFix = channel.unary_unary(
        '/api.VirExOtcApi/futuresPositionFix',
        request_serializer=vir__exchange__api__service__pb2.FuturesPositionFix.SerializeToString,
        response_deserializer=vir__exchange__api__service__pb2.FuturesPositionFixResult.FromString,
        )


class VirExOtcApiServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getExMarketDepth(self, request, context):
    """get exchange market aggr depth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOtcMarketDepth(self, request, context):
    """get otc market aggr depth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getMarketDepth(self, request, context):
    """get target exchange market depth
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getAccountLeft(self, request, context):
    """get target exchange account left
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createBuyOrder(self, request, context):
    """create buy order on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createSellOrder(self, request, context):
    """create sell order on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createBuyLimitMakerOrder(self, request, context):
    """create buy order on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def createSellLimitMakerOrder(self, request, context):
    """create sell order on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def cannelOrder(self, request, context):
    """cannel order on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def checkOrder(self, request, context):
    """check order on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getOrdersMatchResult(self, request, context):
    """get history order info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getCurrentOrders(self, request, context):
    """get current orders info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def getFinishedOrders(self, request, context):
    """get finished orders info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def kline(self, request, context):
    """get kline info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def klineRSI(self, request, context):
    """get kline rsi index info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def klineKDJ(self, request, context):
    """get kline kdj index info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def klineBOLL(self, request, context):
    """get kline boll index info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresTicker(self, request, context):
    """get futuress market information on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresDepth(self, request, context):
    """get depth information of futures market on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresKLine(self, request, context):
    """get futures kline info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresKLineRSI(self, request, context):
    """get futures kline rsi index info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresKLineKDJ(self, request, context):
    """get futures kline kdj index info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresKLineBOLL(self, request, context):
    """get kline boll index info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresIndex(self, request, context):
    """get futures index on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresEstimatedPrice(self, request, context):
    """get futures estimated price on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresTrade(self, request, context):
    """create buy/sell futures order on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresCancel(self, request, context):
    """futures cancel order on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresBatchCancel(self, request, context):
    """futures batch cancel orders on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresCheckOrder(self, request, context):
    """get futures order info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresOrders(self, request, context):
    """get futures orders info on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresUserInfoFix(self, request, context):
    """get futures userInfo fix on target exchange
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def futuresPositionFix(self, request, context):
    """get futures position fix on target exchage
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_VirExOtcApiServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getExMarketDepth': grpc.unary_unary_rpc_method_handler(
          servicer.getExMarketDepth,
          request_deserializer=vir__exchange__api__service__pb2.DepthInfo.FromString,
          response_serializer=vir__exchange__api__service__pb2.TradeInfos.SerializeToString,
      ),
      'getOtcMarketDepth': grpc.unary_unary_rpc_method_handler(
          servicer.getOtcMarketDepth,
          request_deserializer=vir__exchange__api__service__pb2.DepthInfo.FromString,
          response_serializer=vir__exchange__api__service__pb2.TradeInfos.SerializeToString,
      ),
      'getMarketDepth': grpc.unary_unary_rpc_method_handler(
          servicer.getMarketDepth,
          request_deserializer=vir__exchange__api__service__pb2.MarketInfo.FromString,
          response_serializer=vir__exchange__api__service__pb2.MarketInfoResult.SerializeToString,
      ),
      'getAccountLeft': grpc.unary_unary_rpc_method_handler(
          servicer.getAccountLeft,
          request_deserializer=vir__exchange__api__service__pb2.AssetInfo.FromString,
          response_serializer=vir__exchange__api__service__pb2.AssetResult.SerializeToString,
      ),
      'createBuyOrder': grpc.unary_unary_rpc_method_handler(
          servicer.createBuyOrder,
          request_deserializer=vir__exchange__api__service__pb2.OrderInfo.FromString,
          response_serializer=vir__exchange__api__service__pb2.OrderResult.SerializeToString,
      ),
      'createSellOrder': grpc.unary_unary_rpc_method_handler(
          servicer.createSellOrder,
          request_deserializer=vir__exchange__api__service__pb2.OrderInfo.FromString,
          response_serializer=vir__exchange__api__service__pb2.OrderResult.SerializeToString,
      ),
      'createBuyLimitMakerOrder': grpc.unary_unary_rpc_method_handler(
          servicer.createBuyLimitMakerOrder,
          request_deserializer=vir__exchange__api__service__pb2.OrderInfo.FromString,
          response_serializer=vir__exchange__api__service__pb2.OrderResult.SerializeToString,
      ),
      'createSellLimitMakerOrder': grpc.unary_unary_rpc_method_handler(
          servicer.createSellLimitMakerOrder,
          request_deserializer=vir__exchange__api__service__pb2.OrderInfo.FromString,
          response_serializer=vir__exchange__api__service__pb2.OrderResult.SerializeToString,
      ),
      'cannelOrder': grpc.unary_unary_rpc_method_handler(
          servicer.cannelOrder,
          request_deserializer=vir__exchange__api__service__pb2.OrderDetail.FromString,
          response_serializer=vir__exchange__api__service__pb2.OrderDetailResult.SerializeToString,
      ),
      'checkOrder': grpc.unary_unary_rpc_method_handler(
          servicer.checkOrder,
          request_deserializer=vir__exchange__api__service__pb2.OrderDetail.FromString,
          response_serializer=vir__exchange__api__service__pb2.OrderDetailResult.SerializeToString,
      ),
      'getOrdersMatchResult': grpc.unary_unary_rpc_method_handler(
          servicer.getOrdersMatchResult,
          request_deserializer=vir__exchange__api__service__pb2.OrderMatcher.FromString,
          response_serializer=vir__exchange__api__service__pb2.OrderMatcherResult.SerializeToString,
      ),
      'getCurrentOrders': grpc.unary_unary_rpc_method_handler(
          servicer.getCurrentOrders,
          request_deserializer=vir__exchange__api__service__pb2.CurrentOrder.FromString,
          response_serializer=vir__exchange__api__service__pb2.CurrentOrderResult.SerializeToString,
      ),
      'getFinishedOrders': grpc.unary_unary_rpc_method_handler(
          servicer.getFinishedOrders,
          request_deserializer=vir__exchange__api__service__pb2.FinishedOrder.FromString,
          response_serializer=vir__exchange__api__service__pb2.FinishedOrderResult.SerializeToString,
      ),
      'kline': grpc.unary_unary_rpc_method_handler(
          servicer.kline,
          request_deserializer=vir__exchange__api__service__pb2.KLine.FromString,
          response_serializer=vir__exchange__api__service__pb2.KLineResult.SerializeToString,
      ),
      'klineRSI': grpc.unary_unary_rpc_method_handler(
          servicer.klineRSI,
          request_deserializer=vir__exchange__api__service__pb2.KLineRSI.FromString,
          response_serializer=vir__exchange__api__service__pb2.KLineRSIResult.SerializeToString,
      ),
      'klineKDJ': grpc.unary_unary_rpc_method_handler(
          servicer.klineKDJ,
          request_deserializer=vir__exchange__api__service__pb2.KLineKDJ.FromString,
          response_serializer=vir__exchange__api__service__pb2.KLineKDJResult.SerializeToString,
      ),
      'klineBOLL': grpc.unary_unary_rpc_method_handler(
          servicer.klineBOLL,
          request_deserializer=vir__exchange__api__service__pb2.KLineBOLL.FromString,
          response_serializer=vir__exchange__api__service__pb2.KLineBOLLResult.SerializeToString,
      ),
      'futuresTicker': grpc.unary_unary_rpc_method_handler(
          servicer.futuresTicker,
          request_deserializer=vir__exchange__api__service__pb2.FuturesTicker.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesTickerResult.SerializeToString,
      ),
      'futuresDepth': grpc.unary_unary_rpc_method_handler(
          servicer.futuresDepth,
          request_deserializer=vir__exchange__api__service__pb2.FuturesDepth.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesDepthResult.SerializeToString,
      ),
      'futuresKLine': grpc.unary_unary_rpc_method_handler(
          servicer.futuresKLine,
          request_deserializer=vir__exchange__api__service__pb2.FuturesKLine.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesKLineResult.SerializeToString,
      ),
      'futuresKLineRSI': grpc.unary_unary_rpc_method_handler(
          servicer.futuresKLineRSI,
          request_deserializer=vir__exchange__api__service__pb2.FuturesKLineRSI.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesKLineRSIResult.SerializeToString,
      ),
      'futuresKLineKDJ': grpc.unary_unary_rpc_method_handler(
          servicer.futuresKLineKDJ,
          request_deserializer=vir__exchange__api__service__pb2.FuturesKLineKDJ.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesKLineKDJResult.SerializeToString,
      ),
      'futuresKLineBOLL': grpc.unary_unary_rpc_method_handler(
          servicer.futuresKLineBOLL,
          request_deserializer=vir__exchange__api__service__pb2.FuturesKLineBOLL.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesKLineBOLLResult.SerializeToString,
      ),
      'futuresIndex': grpc.unary_unary_rpc_method_handler(
          servicer.futuresIndex,
          request_deserializer=vir__exchange__api__service__pb2.FuturesIndex.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesIndexResult.SerializeToString,
      ),
      'futuresEstimatedPrice': grpc.unary_unary_rpc_method_handler(
          servicer.futuresEstimatedPrice,
          request_deserializer=vir__exchange__api__service__pb2.FuturesEstimatedPrice.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesEstimatedPriceResult.SerializeToString,
      ),
      'futuresTrade': grpc.unary_unary_rpc_method_handler(
          servicer.futuresTrade,
          request_deserializer=vir__exchange__api__service__pb2.FuturesTrade.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesTradeResult.SerializeToString,
      ),
      'futuresCancel': grpc.unary_unary_rpc_method_handler(
          servicer.futuresCancel,
          request_deserializer=vir__exchange__api__service__pb2.FuturesCancel.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesCancelResult.SerializeToString,
      ),
      'futuresBatchCancel': grpc.unary_unary_rpc_method_handler(
          servicer.futuresBatchCancel,
          request_deserializer=vir__exchange__api__service__pb2.FuturesBatchCancel.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesBatchCancelResult.SerializeToString,
      ),
      'futuresCheckOrder': grpc.unary_unary_rpc_method_handler(
          servicer.futuresCheckOrder,
          request_deserializer=vir__exchange__api__service__pb2.FuturesCheckOrder.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesCheckOrderResult.SerializeToString,
      ),
      'futuresOrders': grpc.unary_unary_rpc_method_handler(
          servicer.futuresOrders,
          request_deserializer=vir__exchange__api__service__pb2.FuturesOrders.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesOrdersResult.SerializeToString,
      ),
      'futuresUserInfoFix': grpc.unary_unary_rpc_method_handler(
          servicer.futuresUserInfoFix,
          request_deserializer=vir__exchange__api__service__pb2.FuturesUserInfoFix.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesUserInfoFixResult.SerializeToString,
      ),
      'futuresPositionFix': grpc.unary_unary_rpc_method_handler(
          servicer.futuresPositionFix,
          request_deserializer=vir__exchange__api__service__pb2.FuturesPositionFix.FromString,
          response_serializer=vir__exchange__api__service__pb2.FuturesPositionFixResult.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.VirExOtcApi', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
